# Generated by Django 6.0.2 on 2026-03-15 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequirement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Requirement', 'verbose_name_plural': 'Job Requirements'},
        ),
        migrations.RenameField(
            model_name='jobrequirement',
            old_name='title',
            new_name='job_title',
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='job_pdf',
            field=models.FileField(blank=True, null=True, upload_to='job_pdfs/'),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='job_type',
            field=models.CharField(default='internship', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='location',
            field=models.CharField(default='Ahmedabad', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='salary',
            field=models.CharField(default='Not Specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='selection_process',
            field=models.TextField(default='Selection Process Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='skills',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='vacancies',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='eligibility',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], default='OPEN', max_length=10),
        ),
    ]
