# Generated by Django 6.0.2 on 2026-03-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companyprofile_company_size_and_more'),
        ('jobs', '0002_alter_jobrequirement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='companies.companyprofile'),
        ),
    ]
