# Generated by Django 6.0.2 on 2026-03-20 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobrequirement_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirement',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
