# Generated by Django 6.0.2 on 2026-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobrequirement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirement',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('EXPIRED', 'Expired'), ('DRAFT', 'Draft')], default='OPEN', max_length=10),
        ),
    ]
