# Generated by Django 6.0.2 on 2026-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='passport_photo',
            field=models.FileField(upload_to='passport_photo/'),
        ),
    ]
