# Generated by Django 6.0.2 on 2026-03-25 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobrequirement_status'),
        ('students', '0002_alter_studentprofile_passport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(help_text='Comma separated skills'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], db_index=True, default='APPLIED', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobrequirement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='students_jo_student_1ee6d0_idx'), models.Index(fields=['job', 'status'], name='students_jo_job_id_ab7bf1_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'job'), name='unique_student_job_application')],
            },
        ),
    ]
