# Generated by Django 6.0.2 on 2026-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_skills_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('UNDER_REVIEW', 'Under Review'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], db_index=True, default='APPLIED', max_length=20),
        ),
    ]
