# Generated by Django 6.0.2 on 2026-04-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('INTERVIEW', 'Interview Scheduled'), ('INTERVIEW_HOLD', 'Interview Hold'), ('INTERVIEW_REJECTED', 'Rejected After Interview'), ('SELECTED', 'Selected')], db_index=True, default='APPLIED', max_length=20),
        ),
    ]
