# Generated by Django 6.0.2 on 2026-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_jobapplication_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
