# Generated by Django 6.0.2 on 2026-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_jobapplication_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('SHORTLIST_REJECTED', 'Rejected After Shortlist'), ('INTERVIEW', 'Interview Scheduled'), ('INTERVIEW_HOLD', 'Interview Hold'), ('INTERVIEW_REJECTED', 'Rejected After Interview'), ('SELECTED', 'Selected')], db_index=True, default='APPLIED', max_length=20),
        ),
    ]
