# Generated by Django 6.0.2 on 2026-04-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlistedstudent',
            name='job',
        ),
        migrations.RemoveField(
            model_name='shortlistedstudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='ShortlistedStudent',
        ),
    ]
