# Generated by Django 6.0.2 on 2026-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placement_cell', '0002_remove_shortlistedstudent_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the user', max_length=100)),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional contact number', max_length=15, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('company', 'Company'), ('visitor', 'Visitor')], default='visitor', help_text='Role of the user submitting the message', max_length=20)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=100)),
                ('message', models.TextField(help_text='Detailed message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was created')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
