# Generated by Django 6.0.2 on 2026-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('placement_cell', 'Placement Cell'), ('student', 'Student'), ('company', 'Company')], max_length=20),
        ),
    ]
