# Generated by Django 6.0.2 on 2026-03-01 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('cp_name', models.CharField(max_length=150)),
                ('cp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cp_phone', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=150)),
                ('reg_certificate', models.FileField(upload_to='copmpany_certificates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='companies_c_status_731891_idx'), models.Index(fields=['industry'], name='companies_c_industr_789198_idx')],
            },
        ),
    ]
