# Generated by Django 6.0.2 on 2026-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(choices=[('1-50', '1-50 Employees'), ('51-200', '51-200 Employees'), ('201-500', '201-500 Employees'), ('500+', '500+ Employees')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='reg_certificate',
            field=models.FileField(upload_to='company_certificates/'),
        ),
    ]
