# Generated by Django 6.0.2 on 2026-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companyprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hold', 'On Hold')], db_index=True, default='pending', max_length=20),
        ),
    ]
