# Generated by Django 6.0.2 on 2026-04-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_interview'),
        ('students', '0004_alter_jobapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='students.jobapplication')),
            ],
            options={
                'verbose_name': 'Selection Result',
                'verbose_name_plural': 'Selection Results',
                'ordering': ['-declared_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortlistedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('shortlisted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist', to='students.jobapplication')),
            ],
            options={
                'verbose_name': 'Shortlisted Student',
                'verbose_name_plural': 'Shortlisted Students',
                'ordering': ['-shortlisted_at'],
            },
        ),
    ]
